# Generated by Django 3.2.3 on 2021-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210715_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='drummer',
            name='drums',
            field=models.ManyToManyField(to='main_app.Drum'),
        ),
    ]
